// import { Roboto } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
import "./globals.css";
import Footer from '@/components/shared/Footer';


// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// })
const open_sans = Open_Sans({
  weight:'400',
  // style:'italic',
  subsets : ["latin"]
})

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={open_sans.className}
      >
      
      
      
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
