// import { Roboto } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
import "./globals.css";


// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// })
const open_sans = Open_Sans({
  weight:'400',
  // style:'italic',
  subsets : ["latin"]
})

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={open_sans.className}
      >
       <div className="w-full">
      
       </div>
        <div className="max-w-7xl mx-auto mt-4">{children}</div>
      </body>
    </html>
  );
}
